CoffeeHouse/Controllers/CoffeeHouseController.cs
using CoffeeHouse.Data;
using Microsoft.AspNetCore.Mvc;
using CoffeeHouse.Models;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace CoffeeHouse.Controllers
{
    public class CoffeeHouseController : Controller
    {
        CoffeeHouseContext db;
        public CoffeeHouseController(CoffeeHouseContext db)
        {
            this.db = db;
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Menu(int? page)
        {
            int pageSize = 2;
            int pageNumber = page==null||page<0?1:page.Value;
            var lstsanpham = db.Products.AsNoTracking().OrderBy(x=>x.IdProduct);
            PagedList<Products> lst = new PagedList<Products>(lstsanpham, pageNumber, pageSize);
            return View(lst);
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Shop()
        {
            return View();
        }

        public IActionResult Shop_Cart()
        {
            return View();
        }

        public IActionResult Shop_Checkout()
        {
            return View();
        }

        public IActionResult Shop_Single()
        {
            return View();
        }

        public IActionResult Blog()
        {
            return View();
        }

        public IActionResult Blog_Single()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Join()
        {
            return View();
        }
    }
}

CoffeeHouse/ViewComponents/LoaiSPMenuViewComponent.cs
using CoffeeHouse.Models;
using CoffeeHouse.Repository;
using Microsoft.AspNetCore.Mvc;
namespace CoffeeHouse.ViewComponents
{
    public class LoaiSPMenuViewComponent:ViewComponent
    {
        private readonly ILoaiSPRepository _loaiSp;
        public LoaiSPMenuViewComponent(ILoaiSPRepository loaiSpRepository)
        {
            _loaiSp = loaiSpRepository;
        }
        public IViewComponentResult Invoke()
        {
            var loaisp = _loaiSp.GetAllCategories().OrderBy(x => x.Name);
            return View(loaisp);
        }
    }
} 

CoffeeHouse/Views/CoffeeHouse/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="breadcumb" style="background: url(/images_icon/about_us/breadcumb.jpg);">
    <h2 class="breadcumb-title">About Us</h2>
</div>

<div class="about-us py-120">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="about-img">
                    <img src="~/images_icon/about_us/mem1.png" alt="">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="about-right">
                    <div class="text-heading mb-3">
                        <span class="text-title-tagline">About Us</span>
                        <h2 class="text-title">
                            Fresh Quality And Organic Tasty Coffee House For You
                        </h2>
                    </div>
                    <p class="about-text">
                        There are many variations of passages of Lorem Ipsum available, but the majority have
                        suffered alteration in some form, by injected humour, or randomised words which don't
                        look even slightly believable.
                    </p>
                    <div class="about-list-wrapper">
                        <ul class="about-list margin-btm">
                            <li>
                                <i class="faicon icofont-check-alt"></i>
                                At vero eos et accusamus et iusto odio
                            </li>
                            <li>
                                <i class="faicon icofont-check-alt"></i>
                                Established fact that a reader will be distracted
                            </li>
                            <li>
                                <i class="faicon icofont-check-alt"></i>
                                Sed ut perspiciatis unde omnis iste natus sit
                            </li>
                        </ul>
                    </div>
                    <a href="#" class="theme-btn mt-4">Discover More</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="counter-area pt-50 pb-50">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-sm-6">
                <div class="counter-box">
                    <div class="icon">
                        <img src="~/images_icon/counter/branch.svg" alt="">
                    </div>
                    <div>
                        <span class="counter" data-count-from="300" data-count-to="1500"
                              data-count-speed="100"></span>
                        <h6 class="title">+ Total Branches</h6>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="counter-box">
                    <div class="icon">
                        <img src="~/images_icon/counter/customer.svg" alt="">
                    </div>
                    <div>
                        <span class="counter" data-count-from="0" data-count-to="250"
                              data-count-speed="30"></span>
                        <h6 class="title">+ Happy Customers</h6>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="counter-box">
                    <div class="icon">
                        <img src="~/images_icon/counter/chef.svg" alt="">
                    </div>
                    <div>
                        <span class="counter" data-count-from="0" data-count-to="120"
                              data-count-speed="30"></span>
                        <h6 class="title">+ Professional Chefs</h6>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="counter-box">
                    <div class="icon">
                        <img src="~/images_icon/counter/experience.svg" alt="">
                    </div>
                    <div>
                        <span class="counter" data-count-from="0" data-count-to="50"
                              data-count-speed="10"></span>
                        <h6 class="title">+ Years Of Experience</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<div class="choose py-120" style="padding-top: 10px;">
    <div class="choose-shape-1"><img src="~/images_icon/whychoose/list_shape/ls1.png" alt=""></div>
    <div class="choose-shape-2"><img src="~/images_icon/whychoose/list_shape/ls2.png" alt=""></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="choose-content">
                    <div class="text-heading">
                        <span class="text-title-tagline">Why Choose Us</span>
                        <h2 class="text-title mb-10">
                            Coffero Most Out Of Your Favorite & Tasty Coffee House
                        </h2>
                        <p class="pcolor">
                            There are many variations of passages of orem psum available but the majority have
                            suffered alteration in some form by injected humour or randomised words which don't
                            look even slightly believable.
                        </p>
                    </div>
                    <div class="choose-content-wrapper">
                        <div class="choose-item">
                            <div class="choose-item-icon">
                                <img src="~/images_icon/whychoose/list-icon/coffee-beans-1.svg" alt="">
                            </div>
                            <div class="choose-item-text">
                                <h3>Awesome Aroma</h3>
                                <p class="pcolor">
                                    There are many variations of passages of Lorem Ipsum available
                                    but the majority have suffered alteration in some injected.
                                </p>
                            </div>
                        </div>
                        <div class="choose-item">
                            <div class="choose-item-icon">
                                <img src="~/images_icon/whychoose/list-icon/coffee-beans-2.svg" alt="">
                            </div>
                            <div class="choose-item-text">
                                <h3>Pure Grades</h3>
                                <p class="pcolor">
                                    There are many variations of passages of Lorem Ipsum available
                                    but the majority have suffered alteration in some injected.
                                </p>
                            </div>
                        </div>
                        <div class="choose-item">
                            <div class="choose-item-icon">
                                <img src="~/images_icon/whychoose/list-icon/coffee-beans-3.svg" alt="">
                            </div>
                            <div class="choose-item-text">
                                <h3>Healthy Coffee</h3>
                                <p class="pcolor">
                                    There are many variations of passages of Lorem Ipsum available
                                    but the majority have suffered alteration in some injected.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="choose-img">
                    <div class="video-wrapper">
                        <img src="~/images_icon/whychoose/img/chooseimg.jpg" alt="">
                        <a class="play-btn popup-youtube" href="https://www.youtube.com/watch?v=_111P1SRvPc">
                            <i class="icofont-ui-play"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="partner pt-70 pb-70">
    <div class="container">
        <div class="partner-wrapper partner-slider owl-carousel owl-theme">
            <img src="~/images_icon/partner/ptner.png" alt="thumb">
            <img src="~/images_icon/partner/ptner.png" alt="thumb">
            <img src="~/images_icon/partner/ptner.png" alt="thumb">
            <img src="~/images_icon/partner/ptner.png" alt="thumb">
            <img src="~/images_icon/partner/ptner.png" alt="thumb">
            <img src="~/images_icon/partner/ptner.png" alt="thumb">
            <img src="~/images_icon/partner/ptner.png" alt="thumb">
        </div>
    </div>
</div>

CoffeeHouse/Views/CoffeeHouse/Blog.cshtml
@{
    ViewData["Title"] = "Blog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="blog py-120">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-4">
                <div class="blog-item">
                    <div class="blog-item-img">
                        <img src="/images_icon/blog/our_blog/blg1.jpg" alt="Thumb">
                    </div>
                    <div class="blog-item-info">
                        <div class="blog-item-meta">
                            <ul>
                                <li><a href="#"><i class="far fa-user-circle"></i> By Mr.Ecoffee</a></li>
                                <li><a href="#"><i class="far fa-calendar-alt"></i> May 15, 2022</a></li>
                            </ul>
                        </div>
                        <h4 class="blog-title">
                            <a href="https://ecoworld.co/business-coffee-opened-the-first-coffee-shop-in-vietnam.html">
                                There are many variations of the passages available suffered
                            </a>
                        </h4>
                        <a class="blog-btn" href="https://ecoworld.co/business-coffee-opened-the-first-coffee-shop-in-vietnam.html">
                            Read More<i class="fa-sharp fa-solid fa-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4">
                <div class="blog-item">
                    <div class="blog-item-img">
                        <img src="/images_icon/blog/our_blog/blg2.jpg" alt="Thumb">
                    </div>
                    <div class="blog-item-info">
                        <div class="blog-item-meta">
                            <ul>
                                <li><a href="#"><i class="far fa-user-circle"></i> By Alicia Davis</a></li>
                                <li><a href="#"><i class="far fa-calendar-alt"></i> May 15, 2022</a></li>
                            </ul>
                        </div>
                        <h4 class="blog-title">
                            <a href="https://www.allrecipes.com/article/types-of-coffee/">
                                Bean to Cup: Different Types of Coffee, Roasts, and Drinks
                            </a>
                        </h4>
                        <a class="blog-btn" href="https://www.allrecipes.com/article/types-of-coffee/">
                            Read More<i class="fa-sharp fa-solid fa-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4">
                <div class="blog-item">
                    <div class="blog-item-img">
                        <img src="/images_icon/blog/our_blog/blg3.jpg" alt="Thumb">
                    </div>
                    <div class="blog-item-info">
                        <div class="blog-item-meta">
                            <ul>
                                <li><a href="#"><i class="far fa-user-circle"></i> By EcoWorld</a></li>
                                <li><a href="#"><i class="far fa-calendar-alt"></i> May 15, 2022</a></li>
                            </ul>
                        </div>
                        <h4 class="blog-title">
                            <a href="https://retail.economictimes.indiatimes.com/news/food-entertainment/food-services/international-coffee-day-2022-hows-the-coffee-market-brewing-for-tea-loving-india/94574753">
                                International coffee day 2022: How’s the coffee market brewing?
                        </h4>
                        <a class="blog-btn" href="https://retail.economictimes.indiatimes.com/news/food-entertainment/food-services/international-coffee-day-2022-hows-the-coffee-market-brewing-for-tea-loving-india/94574753">
                            Read More<i class="fa-sharp fa-solid fa-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4">
                <div class="blog-item">
                    <div class="blog-item-img">
                        <img src="/images_icon/blog/our_blog/blg4.jpg" alt="Thumb">
                    </div>
                    <div class="blog-item-info">
                        <div class="blog-item-meta">
                            <ul>
                                <li><a href="#"><i class="far fa-user-circle"></i> By Retails</a></li>
                                <li><a href="#"><i class="far fa-calendar-alt"></i> May 15, 2022</a></li>
                            </ul>
                        </div>
                        <h4 class="blog-title">
                            <a href="https://www.theguardian.com/food/2022/sep/27/its-official-coffee-is-good-for-you-just-like-red-wine-dark-chocolate-beer">
                                It’s official! Coffee is good for you – just like red wine, dark chocolate…
                            </a>
                        </h4>
                        <a class="blog-btn" href="https://www.theguardian.com/food/2022/sep/27/its-official-coffee-is-good-for-you-just-like-red-wine-dark-chocolate-beer">
                            Read More<i class="fa-sharp fa-solid fa-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4">
                <div class="blog-item">
                    <div class="blog-item-img">
                        <img src="/images_icon/blog/our_blog/blg5.jpg" alt="Thumb">
                    </div>
                    <div class="blog-item-info">
                        <div class="blog-item-meta">
                            <ul>
                                <li><a href="#"><i class="far fa-user-circle"></i> By Bao Moi</a></li>
                                <li><a href="#"><i class="far fa-calendar-alt"></i> May 15, 2022</a></li>
                            </ul>
                        </div>
                        <h4 class="blog-title">
                            <a href="https://www.medicalnewstoday.com/articles/322649">
                                Coffee and Cancer: A Medical Overview
                            </a>
                        </h4>
                        <a class="blog-btn" href="https://www.medicalnewstoday.com/articles/322649">
                            Read More<i class="fa-sharp fa-solid fa-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4">
                <div class="blog-item">
                    <div class="blog-item-img">
                        <img src="/images_icon/blog/our_blog/blg6.jpg" alt="Thumb">
                    </div>
                    <div class="blog-item-info">
                        <div class="blog-item-meta">
                            <ul>
                                <li><a href="#"><i class="far fa-user-circle"></i> By Kidney</a></li>
                                <li><a href="#"><i class="far fa-calendar-alt"></i> May 15, 2022</a></li>
                            </ul>
                        </div>
                        <h4 class="blog-title">
                            <a href="https://brewminate.com/a-brief-history-of-coffee/">
                                A Brief History of Coffee - Brewminate: A Bold Blend of News
                            </a>
                        </h4>
                        <a class="blog-btn" href="https://brewminate.com/a-brief-history-of-coffee/">
                            Read More<i class="fa-sharp fa-solid fa-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="pagination-area">
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true"><i class="fa-sharp fa-solid fa-angles-left"></i></span>
                        </a>
                    </li>
                    <li class="page-item active"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true"><i class="fa-sharp fa-solid fa-angles-right"></i></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

CoffeeHouse/Views/CoffeeHouse/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="breadcumb" style="background: url(/images_icon/about_us/breadcumb.jpg);">
    <h2 class="breadcumb-title">Contact Us</h2>
</div>
<div class="contact py-120">
    <div class="container">
        <div class="contact-wrapper">
            <div class="row">
                <div class="col-lg-4">
                    <div class="contact-content">
                        <div class="contact-info">
                            <div class="contact-icon">
                                <i class="fa-sharp fa-solid fa-location-dot"></i>
                            </div>
                            <div class="contact-info-content">
                                <h5>Office Address</h5>
                                <p>1st Floor Keangnam - Nam Tu Liem - Ha Noi</p>
                            </div>
                        </div>
                        <div class="contact-info">
                            <div class="contact-icon">
                                <i class="fa-solid fa-phone-flip"></i>
                            </div>
                            <div class="contact-info-content">
                                <h5>Call Us</h5>
                                <p>024 3205 1777</p>
                            </div>
                        </div>
                        <div class="contact-info">
                            <div class="contact-icon">
                                <i class="far fa-envelope"></i>
                            </div>
                            <div class="contact-info-content">
                                <h5>Email Us</h5>
                                <p>
                                    <a href="/cdn-cgi/l/email-protection" class="__cf_email__"
                                       data-cfemail="d7beb9b1b897b2afb6baa7bbb2f9b4b8ba">info@example.com</a>
                                </p>
                            </div>
                        </div>
                        <div class="contact-info">
                            <div class="contact-icon">
                                <i class="fa-regular fa-clock"></i>
                            </div>
                            <div class="contact-info-content">
                                <h5>Office Open</h5>
                                <p>Sun - Fri (08AM - 11PM)</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8 align-self-center">
                    <div class="contact-form">
                        <div class="contact-header">
                            <h2>Feel Free To Contact Us</h2>
                            <p>
                                It is a long established fact that a reader will be distracted by the readable
                                content of a page randomised words which don't look even slightly when looking
                                at its layout.
                            </p>
                        </div>
                        <form action="" id="contact-form">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="name"
                                               placeholder="Your Name" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="email"
                                               placeholder="Your Email" required>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="phone" placeholder="Your Phone"
                                       required>
                            </div>
                            <div class="form-group">
                                <textarea name="message" class="form-control" cols="30" rows="5"
                                          placeholder="Write Your Massage"></textarea>
                            </div>
                            <button type="submit" class="theme-btn">
                                <i class="fa-sharp fa-solid fa-paper-plane"></i>Send Message
                            </button>
                            <div class="col-md-12 mt-3">
                                <div class="form-messege text-success"></div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="contact-map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.362362987847!2d105.78199041502545!3d21.018182186004097!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x313454ab43c0c4db%3A0xdb6effebd6991106!2sKeangnam%20Landmark%20Tower!5e0!3m2!1svi!2s!4v1665634727985!5m2!1svi!2s"
            style="border:0;" allowfullscreen="" loading="lazy"></iframe>
</div>

CoffeeHouse/Views/CoffeeHouse/Login.cshtml
@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="login py-120" style="background-image: url(/images_icon/menu/background/bg.jpeg)">
    <div class="container">
        <div class="col-lg-8 mx-auto reservation-wrapper">
            <div class="row">
                <div class="text-login text-center">
                    <h2 class="text-title">Sign in or create an account</h2>
                </div>
                <div class="col-lg-12 mx-auto">
                    <form action="" id="login-form">
                        <div class="col">
                            <div class="reservation-content">
                                <div class="mx-auto col-lg-9">
                                    <div class="form-group">
                                        <input type="text" name="user" class="form-control"
                                               placeholder="Username or email address">
                                        <div class="error-message" id="user-error"></div>
                                    </div>
                                </div>
                                <div class="mx-auto col-lg-9">
                                    <div class="form-group">
                                        <input type="password" name="password" class="form-control"
                                               placeholder="Password">
                                        <div class="error-message" id="password-error"></div>
                                    </div>
                                </div>
                                <div class="mx-auto col-lg-9">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" id="cat1">
                                        <label class="form-check-label" for="cat1"> Keep me signed in.</label>
                                    </div>
                                </div>
                                <div class="mx-auto col-lg-9">
                                    <a href="" class="login_user">Forgot your username?</a>
                                </div>
                                <div class="mx-auto col-lg-9">
                                    <a href="" class="login_user">Forgot your password?</a>
                                </div>
                                <div class="mx-auto login-btn">
                                    <a href="#" class="logintheme-btn" id="submit-button">Sign in</a>
                                </div>
                                <div class="success-message" id="success-message" style="display: none">
                                    Đăng nhập thành công. Dữ liệu đã được lưu vào Google.
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-4 mx-auto login-joinnow">
            <div class="col">
                <div class="login-join">
                    <p>
                        Join Coffee House to earn free food and drinks, get free refills, pay and order with your
                        phone, and more.
                    </p>
                </div>
                <div class="col-lg-4 mx-auto login-btn">
                    <a href="/CoffeeHouse/Join" class="loginjoin-btn">Join now</a>
                </div>
            </div>
        </div>
    </div>
</div>

CoffeeHouse/Views/CoffeeHouse/Menu.cshtml
@{
    ViewData["Title"] = "Menu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<Products>
<div class="breadcumb" style="background: url(/images_icon/about_us/breadcumb.jpg);">
    <h2 class="breadcumb-title">Our Menu</h2>
</div>

<div class="menu py-120" style="background-image: url(/images_icon/menu/background/bg.jpeg)">
     <div class="container">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <div class="text-heading text-center">
                    <span class="text-title-tagline">Our Menu</span>
                    <h2 class="text-title">Let's Check Our Menu</h2>
                </div>
            </div>
        </div>
        <div class="menu-content">
            <div class="row">
                @await Component.InvokeAsync("LoaiSPMenu");
                <div class="row">
                        @foreach(var item in Model)
                        {
                            <div class="col-lg-6">
                            <div class="menu-item">
                                <div class="menu-item-content">
                                    <div class="menu-img">
                                        <img src="~/images_icon/menu/list_menu/mn1.jpg" alt="">
                                    </div>
                       @*              <div class="menu-img set-bg" data-setbg="@Url.Content("../ProductsImages"+@item.Image)"
                                         style="background-image: url(/images_icon/menu/background/bg.jpeg)">
                                        
                                    </div> *@
                                    <div class="menu-info">
                                        <h5>@item.Name</h5>
                                    </div>
                                </div>
                                <div class="menu-price">@item.Price</div>
                            </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
            @Html.PagedListPager(Model, page => Url.Action("Menu", new{page = page}))
        </div>
    </div> 
</div>